name: flutter_sfu_ws
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.47
  sdp_transform:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
